[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_anchor = "HDYyTAVBJL1JMp3kUukxy784micPpWRMBjBZF9zJQ1cX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aishen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
