[features]
seeds = false
skip-lint = false

[programs.devnet]
hello_anchor = "HphBSRZUiKWettW3AMXZSpm4nB7SH4pjRqRvTHTJdgvs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aishen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
