[features]
seeds = true
skip-lint = false

[programs.devnet]
hello_anchor = "vGsRgLSQh24Jb2BjJkR6TFQGcmq2q9JBwv81qQZoQ4h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/aishen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
